### ISSUE TITLE
help wanted 请教一下 annotation processor

### ISSUE THREAD

**Issue by YSMull** [chiiia12/AnnotationSample#1]
Where can I learn annotation processor, can you recommend related books or 
materials? In addition, how to debug the annotation processor code? It happens at compile time... Thank you!

**Comment by chiiia12** [comment]
@YSMull Thanks for creating issue.
Sorry I'm not Chinese, can you speak English?🙇‍♂️

**Comment by chiiia12** [comment]
@YSMull 
Thanks for rewrite issue's body in English! I got it.

For me, This tutorial is helpful to learn annotation processing.
http://www.baeldung.com/java-annotation-processing-builder

And for debugging processor, I tried following link!
https://stackoverflow.com/questions/31345893/debug-java-annotation-processors-using-intellij-and-maven

Have a try!👍

**Comment by YSMull** [comment]
@chiiia12 Thanks a lot!
